all:
	@echo '=================================================='
	@echo 'Documentation source not distributed here,'
	@echo 'please check it out from the code repository:'
	@echo
	@echo 'http://code.google.com/p/handlatex/source/checkout'
	@echo '=================================================='
	@false
